### ISSUE TITLE
[RFC] Road to 1.0

### ISSUE THREAD

**Issue by dragosprotung** [Speicher210/FunctionalTestBundle#10]
I opened this issue to discuss the goals we want to reach with version 1.0

My vision is that we should drop extending from [liip/functional-test-bundle](https://github.com/liip/LiipFunctionalTestBundle) and partially implement some functionalit it offers.

The main features we should provide are:
- kernel creation
- loading fixtures (using doctrine fixture loader)
- bootstrap file for running tests (resetting DB schema, apply the doctrine transaction listener - only DBs  supported by doctrine)
- making assertions for REST calls
- mocking container services in a way that they can be declared private (Symfony 4 only, for Symfony 3 the still have to be declared public)
- mocking authentication at firewall level
- kernel tests to reduce complexity for functional tests that are not testing controllers
- command line tools for generating tests stubs

Features to provide after 1.0:
- helper methods to testing commands
- extension points for various fixture loaders
- dependent fixtures

Features we should not provide:
- supporting something else than doctrine (extensions can be written by 3rd party)
- backing up the DB and resets after each test (can be achieved with transactions)

**Comment by cezarystepkowski** [comment]
@dragosprotung Thanks for the roadmap, looks good for me!

Please just don't forget about the listener to update the expected output. Later (after 1.0) we could think about extending it for formats different than json (I had already use cases for csv, txt and html).

And could you elaborate more on:

> tests to reduce complexity for functional tests that are not testing controllers

?

**Comment by dragosprotung** [comment]
I was thinking about a few more changes to do before 1.0 that will break BC. I can provide more PR with scenarios.

Example would be to change the signature of `assertRestGetPath()` to include the `data` as an array that can be attached to the URL by using `http_build_query`. This will make it much easier to read the tests but will introduced a BC.

Another thing I would introduce is PHPUnit `Constraint` for doing the assertions. This will make it possible to include even add unit tests for assertions.

Also writing more documentation would be helpful.

**Comment by cezarystepkowski** [comment]
I agree with the changes so we'll wait with tagging 1.0. Feel free to submit more PR.

Maybe we could allow to have query params in both the url (like it is now) and in method signature and then merge them? Then we will not introduce a BC and allow to have tests for path which always have some value in the query that you don't want to test and the rest would be passed as array. Something like that:
```
$path = '/api/something?key=123';
$queryParams = ['key2' => 456];
$this->assertRestGetPath($path, [...], $queryParams);
```

However it might be an overkill as well. And I don't see the BC here as a big problem. What's your opinion?

**Comment by cezarystepkowski** [comment]
Perfect, then BC is not a problem and I agree with you about the order of the arguments.

**Comment by dragosprotung** [comment]
@cezarystepkowski a lot of time has passed since this issue was opened. 
I think great work has been done to improve the library and most of the points have been met.

Is there anything that could break BC that should still be implemented?
Shall we release the one 1.0 version ?

**Comment by cezarystepkowski** [comment]
@dragosprotung I agree that it's time to release version 1.0. I'll go quickly through the library to see if there is anything to clean up. After that we can release.

**Comment by dragosprotung** [comment]
Here is a list of possible things we might want to do:
- remove `PublicContainerServicesForTests` as this behavior is available out of the box from Symfony now.
- bump the dev dependencies.
- drop PHP 7.2 support
- make the `custom-loader` `true` by default in the test stub command

**Comment by cezarystepkowski** [comment]
We should at least drop support for PHP 7.2. We can then use `JSON_THROW_ON_ERROR` for json encoding/decoding.

I would also suggest to bump `doctrine/orm` to `^2.7` and type hint against `\Doctrine\Persistence\ObjectManager` instead of `Doctrine\Common\Persistence\ObjectManager` (that would be a BC break so we should do it before release of 1.0).

**Comment by dragosprotung** [comment]
Using `JSON_THROW_ON_ERROR` is not a good enough reason for me to drop support for PHP 7.2. We are doing some hacks around encoding/decoding json that are not compatible with throwing exceptions anyway.
If we later drop PHP 7.2 it's not considered a BC break, as composer will not allow the installation

Do you have the time to work on bumping `doctrine/orm` to `^2.7` ?

**Comment by dragosprotung** [comment]
One more thing, we could also drop `Speicher210\FunctionalTestBundle\Listener\RestRequestFailTestExpectedOutputFileUpdater` as it's using deprecated PHPUnit functionality and there is already a substitute for it (`Speicher210\FunctionalTestBundle\Extension\RestRequestFailTestExpectedOutputFileUpdater`)

**Comment by cezarystepkowski** [comment]
So let's keep PHP 7.2 for now, unless we'll find some BC break.

I'll make a PR for bumping `doctrine/orm`.

I thought about removing the `RestRequestFailTestExpectedOutputFileUpdater` listener also, we should keep only the extension, I'll make a PR for that too.

**Comment by dragosprotung** [comment]
Now that the 2 changes are there, anything else ?

**Comment by cezarystepkowski** [comment]
Let's remove also `PublicContainerServicesForTests` like you suggested as that could be considered as BC break. Other than that I am fine with releasing.

**Comment by dragosprotung** [comment]
It's done

**Comment by cezarystepkowski** [comment]
Version 1.0.0 is released.

**Comment by dragosprotung** [comment]
Woop woop
