### ISSUE TITLE
Error with mocked private service

### ISSUE THREAD

**Issue by ghost** [Speicher210/FunctionalTestBundle#28]
I updates phpunit from 7.5 to 8.5/9.2, on both new phpunit versions I get the following error message when executing my tests:
> Call to a member function allowsNull() on null

Basically I create a mock phpunit's createMock method:
`$someService = $this->createMock(SomeService::class);`

In the test environment I've created a public alias of this service with prefix test.

The error occurs in vendor/speicher210/functional-test-bundle/src/Test/KernelTestCase.php on row 56:
`if (\PHP_VERSION_ID >= 70400 && ! $property->getType()->allowsNull()) {`

If I add a null check in this condition, everything works fine:
`if (\PHP_VERSION_ID >= 70400 && $property->getType() !== null && ! $property->getType()->allowsNull()) {`

But to be honest I'm not sure if this is the expected behaviour. If you need any further information please let me know.

**Comment by dragosprotung** [comment]
What version of the library are you using ? 

Could you provide maybe a small snippet to reproduce the bug ?

**Comment by ghost** [comment]
I'm using version 1.0.5.
I made a example repository: https://github.com/atlant1s258/functional-test-bundle-mockup
While recreating the problem I investigated further. I think the problem is with setting up mocked services in setUp method. The error occurs on the tearDown of phpunit.

**Comment by dragosprotung** [comment]
Thank you for the example repo. It helped.
Not sure how I missed this, but apparently you can get `null` from `$property->getType()`

I pushed a fixed on `1.x` branch. Please try it out. It should work (in the end it has the solution you proposed :smiley: )
If you have no issues any more I will tag a new release

**Comment by ghost** [comment]
I tested it with the fixed 1.x branch and it works fine. I have no more issues.
Thank you.
